# Generated by Django 4.1.6 on 2023-04-03 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_url', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('current_status', models.CharField(max_length=50)),
                ('offer', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('mobile', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=30)),
                ('password', models.CharField(default=None, max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('pin', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.IntegerField()),
                ('number_product', models.IntegerField()),
                ('date', models.DateField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='mybag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_product', models.IntegerField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.product')),
            ],
        ),
    ]
