# Generated by Django 4.1.6 on 2023-04-26 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='order_product',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.CharField(max_length=100)),
                ('number_product', models.IntegerField()),
                ('date', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_url', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('offer', models.IntegerField(default=0)),
                ('product_type', models.CharField(default='non vage', max_length=100)),
                ('location', models.CharField(default='Delhi', max_length=100)),
                ('number_count', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('mobile', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=300)),
                ('pin', models.IntegerField()),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('Reviews_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.CharField(max_length=10)),
                ('review', models.CharField(max_length=500)),
                ('time_created', models.CharField(max_length=100)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.order_product')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.product')),
            ],
        ),
        migrations.AddField(
            model_name='order_product',
            name='mobile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail'),
        ),
        migrations.AddField(
            model_name='order_product',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.product'),
        ),
        migrations.CreateModel(
            name='mybag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_product', models.IntegerField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='iswishlist',
            fields=[
                ('loveid', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.product')),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail')),
            ],
        ),
        migrations.CreateModel(
            name='card_info',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=50)),
                ('expiry', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=4)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail')),
            ],
        ),
    ]
