# Generated by Django 4.1.6 on 2023-04-16 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='property_id',
            new_name='product_id',
        ),
    ]
