# Generated by Django 4.1.6 on 2023-04-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='city',
            field=models.CharField(default='Jalpaiguri', max_length=100),
        ),
    ]
