# Generated by Django 4.1.6 on 2023-04-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='last_name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='mobile',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
