# Generated by Django 4.1.6 on 2023-04-18 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0002_rename_property_id_reviews_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='order_id',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
