# Generated by Django 4.1.6 on 2023-04-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0002_alter_user_detail_last_name_alter_user_detail_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybag',
            name='mobile',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='mybag',
            name='product_id',
            field=models.CharField(max_length=100),
        ),
    ]
