# Generated by Django 4.1.6 on 2023-04-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0003_alter_order_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
