# Generated by Django 4.1.6 on 2023-04-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0005_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_count',
            field=models.IntegerField(default=10),
        ),
    ]
