# Generated by Django 4.1.6 on 2023-04-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0006_alter_order_product_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='Delhi', max_length=100),
        ),
        migrations.AlterField(
            model_name='order_product',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
