# Generated by Django 4.1.6 on 2023-04-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0007_remove_product_current_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
