# Generated by Django 4.1.6 on 2023-04-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0007_alter_user_detail_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_detail',
            name='pin',
            field=models.CharField(max_length=100),
        ),
    ]
