# Generated by Django 4.1.6 on 2023-04-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0007_product_location_alter_order_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='iswishlist',
            fields=[
                ('loveid', models.AutoField(primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=100)),
            ],
        ),
    ]
