# Generated by Django 4.1.6 on 2023-04-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0008_remove_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='error', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.CharField(default='error', max_length=200),
        ),
    ]
