# Generated by Django 4.1.6 on 2023-05-02 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0009_alter_user_detail_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='No', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.CharField(default='No', max_length=200),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='password',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.CreateModel(
            name='daily_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_type', models.CharField(default='none', max_length=100)),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.product')),
            ],
        ),
    ]
