# Generated by Django 4.1.6 on 2023-04-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0009_alter_product_price_alter_product_product_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='adminuser',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
