# Generated by Django 4.1.6 on 2023-05-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0010_alter_product_product_name_alter_product_product_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
