# Generated by Django 4.1.6 on 2023-04-25 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0010_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.user_detail')),
            ],
        ),
    ]
