# Generated by Django 4.1.6 on 2023-05-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0011_reviews_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_user',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=300)),
                ('Restaurant_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
            ],
        ),
    ]
