# Generated by Django 4.1.6 on 2023-05-06 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0013_restaurant_user_first_name_restaurant_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='email',
            field=models.ForeignKey(default='bg5050525@gmail.com', on_delete=django.db.models.deletion.CASCADE, to='all_api.restaurant_user'),
        ),
    ]
