# Generated by Django 4.1.6 on 2023-05-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0014_product_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_product',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
