# Generated by Django 4.1.6 on 2023-05-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0016_product_restaurant_name_alter_order_product_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isdeleted',
            field=models.BooleanField(default=False),
        ),
    ]
