# Generated by Django 4.1.6 on 2023-05-10 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0017_product_isdeleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='image',
        ),
    ]
