# Generated by Django 4.1.6 on 2023-05-10 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0018_remove_reviews_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_product',
        ),
    ]
