# Generated by Django 4.1.6 on 2023-05-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0019_delete_daily_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='image_detail',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_data')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_api.product')),
            ],
        ),
    ]
