# Generated by Django 4.1.6 on 2023-05-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_api', '0020_image_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Restaurant_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_url',
            field=models.CharField(default='No', max_length=2000),
        ),
    ]
